pool:
   idleConnectionTestPeriod : 60
   idleMaxAge : 240
   maxConnectionsPerPartition : 9
   minConnectionsPerPartition : 3
   partitionCount : 3
   acquireIncrement : 2
   statementsCacheSize : 100
   releaseHelperThreads : 3
   queryExecuteTimeLimitInMs : 3000

common:
   type: mysql
   user: test
   pwd: secret

idpolicy: redis
dbns: saas_%04d

shard:
   - name: server1
     host: 127.0.0.1:3306
     dbidx: 1,2

   - name: server2
     host: 127.0.0.1:3306
     dbidx: 3,4